site_name: Introduction to Python
nav:
  - 'Preparation':
    - 'Installation': './preparation/installation.md'
  - 'Basic Python':
    - 'Primitives': './basic-python/primitives.md'
  - 'Command Line and Git':
    - 'Command Line': './command-line-and-git/command-line.md'
    - 'Git': './command-line-and-git/git.md'
  - 'Intermediate Python':
    - 'Clean and Pythonic Code': './intermediate-python/clean-code.md'
    # - 'Variables': './basic-python/variables.md'
    # - 'Data Types': './basics/data_types.md'
    # - 'Operators': './basics/operators.md'
    # - 'Control Flow': './basics/control_flow.md'
    # - 'Functions': './basics/functions.md'
    # - 'Classes': './basics/classes.md'
    # - 'Modules': './basics/modules.md'
    # - 'Packages': './basics/packages.md'
    # - 'Errors': './basics/errors.md'
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
copyright: Copyright &copy; 2023 Ian Chen
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details