site_name: Introduction to Python
nav:
  - 'Preparation':
    - 'Installation': './preparation/installation.md'
  - 'Basic Python':
    - 'Introduction': './basic-python/introduction.md'
    - 'Write and Run Python Code': './basic-python/write-and-run-python-code.md'
    - 'Primitives': './basic-python/primitives.md'
    - 'Variable Scope': './basic-python/variable-scope.md'
    - 'Projects':
      - 'Data Processing': './basic-python/projects/data-processing.md'
      - 'Tic Tac Toe Game': './basic-python/projects/tic-tac-toe.md'
  - 'Command Line and Git':
    - 'Command Line': './command-line-and-git/command-line.md'
    - 'Git': './command-line-and-git/git.md'
  - 'Intermediate Python':
    - 'Clean and Pythonic Code': './intermediate-python/clean-code.md'
    - 'Object Oriented Programming': './intermediate-python/oop.md'
  - 'Advanced Python':
    - 'Concurrency': './advanced-python/concurrency.md'

    # - 'Variables': './basic-python/variables.md'
    # - 'Data Types': './basics/data_types.md'
    # - 'Operators': './basics/operators.md'
    # - 'Control Flow': './basics/control_flow.md'
    # - 'Functions': './basics/functions.md'
    # - 'Classes': './basics/classes.md'
    # - 'Modules': './basics/modules.md'
    # - 'Packages': './basics/packages.md'
    # - 'Errors': './basics/errors.md'
theme:
  name: material
  features:
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: Copyright &copy; 2023 Ian Chen
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra_javascript:
  - assets/javascripts/posthog.js
  - https://www.googletagmanager.com/gtag/js?id=G-XT28GK2X8V
  - assets/javascripts/ga.js